### ISSUE TITLE
Next update again

### ISSUE THREAD

**Issue by tkapis** [KozGit/DOOM-3-BFG-VR#215]
Hi KozGit, it would be great if you could release the updated version that you have at this moment or least give an idea of when it will be released. Thanks.

**Comment by AerowynX** [comment]
back in April it was soon.. soooo 2020? haha :)  The guys doing the HL2 VR mod also said very soon for their release almost 6 months ago now..  when it comes to free mods life stuff generally comes up since most all these guys are just doing this in their spare time.. what happened to all these living in their parents basement nothing to do hacker types these days heh

**Comment by cercata** [comment]
I'm eager too ... but you know, when people don't get a wage on this, it can be delayed forever.
I'll be happy if it just releases one day :)

**Comment by formicsapien** [comment]
Is there any way to get a 0.22 build so the save game issue is fixed?  Or instructions on how to build?

**Comment by AerowynX** [comment]
.22 doesn't fix the save issue he had said anyway

**Comment by 10101000** [comment]
Hi, I've compiled from the master branch as of today (10-09-2017) to produce V0.022-Alpha with LibOVR version 1.18.0 and OpenVR 1.0.10 (master). The FFmpeg version referenced in the build instructions is no longer available for download so I've used the versions from the 021 release (as well as OpenAL). The installer was created using Nullsoft Install System v3.02.1. So far it's working quite well for me. It has resolved the saved game loading issues that I'd experienced. Enjoy!

Get it [here](https://github.com/10101000/DOOM-3-BFG-VR/releases/tag/V0.022-Alpha).

@formicsapien The build instructions are posted in the README.

**Comment by cercata** [comment]
Thanks @10101000

**Comment by CylonSurfer** [comment]
@10101000 - Game still crashes for me while trying to load my 'Communications Transfer' save.

**Comment by 10101000** [comment]
@CylonSurfer I've not made it this far yet. It has however fixed the "grayed out" saved game issue for me. Perhaps this is a bug that hasn't yet been fixed in the master branch or a problem with a texture pack/mod.

**Comment by formicsapien** [comment]
@10101000 Haha, guess I should've looked before asking!  In any case, awesome work, and thanks!!

**Comment by tkapis** [comment]
@10101000 All my problems seem to be solved with this build, fantastic, thanks.

**Comment by MastaFoo** [comment]
Does this exe include the fix for AMD machines that is supposed to be in the next build? I have the fixed amd exe we were to use in the meantime if it doesnt

**Comment by 10101000** [comment]
It [does](https://github.com/KozGit/DOOM-3-BFG-VR/commit/e9daddb651b6ab6fced6944d2ef466bb70cbf7e9). To view all commits added since 0.021 click [here](https://github.com/KozGit/DOOM-3-BFG-VR/compare/V0.021-Alpha...master). I can't wait for the official release. Until then some of these fixes are worth using the unofficial build like saved game loading, item scaling, head height persistence, player model improvements.

**Comment by KozGit** [comment]
Look at you eager beavers :)  

Quick update - I just pushed a bunch of changes:

Fixed the cutscenes - no more completely broken animations.  This was actually a ton of work and took quite a while - had to update  the camera and animation files for all the scenes.  Main campaign only so far. ( There are three cutscene modes now, immersive, cropped, and projected.  Not in the menus yet, use vr_cinematics to select ) 

Updated the statwatch to display health and armor bars more clearly, and added health/armor icons to the top.  ( Stats and armor indicated by vertical bars on the left and right of the watch display. )

Fixed a bug with in game gui rendering that caused mirrors to black out if a weapon gui or the statwatch came into view at the same time.  This bug also caused some in game displays/monitors to have a blank screen instead of their guis, and caused the security monitors not to work.  ( Thought it was fixed before, now it's really fixed. )

Hacked in teleportation support during the final boss fight.

Bunch of other fixes.

If you guys are playing the new build and using touch controllers, you can play with enabling hand poses by setting vr_useHandPoses to 1.  Cant really interact with the world yet other than guis but hey it's a start.  ( You may want to change the control bindings if you do this.  I bound run to the left grip, flashlight to the left trigger, and crouch to left stick press ).  

You can change the origin of the laser sight with vr_laserSightUseOffset to be either the barrel or lasersight.

Added a push to talk button for voice commands. ( vr_voicePushToTalk to enable, then bind to a button in controls->bindings)

Body can auto hide now when crouching. ( vr_crouchHideBody )

Added option for instant acceleration/deceleration ( vr_instantAccel ) 

You can choke the shotgun to reduce the spread ( vr_shotgunChoke ) ( this can make the shotgun too powerful if you abuse it ) 

Added a headshot multiplier ( vr_headshotMultiplier ).  I think I'm going to change this to pistol only so you can still drop the zombie maintenance guys with a headshot, but it's too powerful when you get bigger weapons.  You'll probably want to change this to 1 or at least reduce it from the default. 

Updated player body IK, and torso direction now also follows view/hand directions.

There are some things I need to clean up before release. The orientation of the loading screens between levels is broken. The new code for handling player leaning needs to be cleaned up.  Autosaved games break the weapon scale when loaded.  And I need to add the new options to the menus.  None of these are big deals, and shouldn't take much to straighten out. ( No modeling/animating thankfully! )  

Let me know what bugs you find.  Unless you find some showstoppers I'll release late next week. 

( I would ask a favor though - if you're running the newly compiled version have fun with it, but I would ask that you don't post links to it all over the place - just makes my life harder. Thanks! )

Oh, and thanks again for being patient.

**Comment by cercata** [comment]
Wow, this is gonna be more polished than most of VR commercial games !!!!!

Thanx dude, good work !!!!

**Comment by formicsapien** [comment]
@KozGit sweat f****** deal man!  Like cercata was saying, this is the best VR mod.  You're the best!!!!  You should post this on reddit.

**Comment by 10101000** [comment]
@KozGit Thanks. I've removed all of the offending posts.

**Comment by 10101000** [comment]
@KozGit Per your statement: _"I would ask that you don't post links to it all over the place"_ I take this to mean that I can post it here?

It compiles successfully. I've posted a new [unofficial release](https://github.com/10101000/DOOM-3-BFG-VR/releases/tag/V0.022-Alpha-Unofficial1) but have not had a chance to run it yet. I've also renamed the installer and zip to indicate that it is unofficial.

**Comment by KozGit** [comment]
Sure, your can post it here, and I appreciate your understanding, thanks!  With the understanding that anyone who uses it is being officially drafted for bug testing :)  I'm working now to polish this up to get the official release out - again targeting late next week.

 Anyone testing out the build @10101000 posted, please feel free to post feedback and bug reports. ( Seriously - let me what's broken.  I did just play the whole Doom 3 campaign start to finish, with lots of saves, to test out the build and cutscenes, so I know the issues I ran into.  When working on this, I tend to wind up playing seated more than I would like - I'm closer to the keyboard and the debugging window.  Feedback from someone giving it a good roomscale workout would be appreciated, especially if you have the player body view enabled. )

**Comment by KozGit** [comment]
@CylonSurfer 

Sounds like either your save game has become corrupt, or an issue with the install of the HD tecture pack you are using.  The index cache error seems like it would be more of an HD issue.  

Few questions - can you play through that location if you start the level from the DEV menu without using a save game? 

Also, can you post a link to the exact download you used for the HD pack.
If you can, please post a copy of your save game file here.  Thx!

( I'm assuming you've tried deleting the 'generated' folder in both the 'base' and 'fully possessed' directories ? )

**Comment by CylonSurfer** [comment]
I am using the HD pack linked from 12-9 release:
https://mega.nz/#!68BUCDZS!PVv4gQSrrP0i6U0Huetqfn-WBXZvpMkDKB81F7_9b7o

I have tried running the level from the dev menu and it loads, however if I save at any point during the 'Communications Transfer' section the save will not load or if I die the game crashes when it tries to reload.

Yup - both 'Generated' folders are deleted. 

Save Game:
[GAME-doom3_10.zip](https://github.com/KozGit/DOOM-3-BFG-VR/files/1384173/GAME-doom3_10.zip)

**Comment by AerowynX** [comment]
HD packs have always been more hassle then they are worth for this game imho.. lost several saves because of them.. unless you are stopping to admire the walls and every detail i'd just skip them.. once the action gets going i don't find it matters much anyway

**Comment by CylonSurfer** [comment]
I don't really want to start over again :) I think I have played to around this point about 4 times over various releases in the past months.

**Comment by AerowynX** [comment]
i actually been in same boat and stopped playing and completely removed the game and any traces of HD pack.. plan on doing a full playthrough once the new version of mod is out with no texture packs this time.

**Comment by CylonSurfer** [comment]
I totally love the game and this mod is superb, one of the best VR experiences out there, but I don't think I could start over again just yet. The early parts of the game have really started to grate on me! I can only imagine what it's like for Samson.

**Comment by tkapis** [comment]
With the newest build the Touch activated GUI is very erratic. When playing the game and opening the menu or the PDA the left hand sometimes appears to the left of centre of the respective GUI and touch no longer works.
Restarting the game or loading a game used to solve the problem but now I get this problem all the time.
I checked settings and the GUI is still touch activated, also tried changing it and then changing it back.

**Comment by KozGit** [comment]
Did by any chance this start when you loaded an autosave game? This is actually the bug I'm chasing down now.

**Comment by tkapis** [comment]
I will try to track down when it happens, I don't think it is only after loading an autosave game.

**Comment by KozGit** [comment]
This happens with every autosave I load.  If I save the game with the PDA corrupt, the immediately load the save, the problem corrects.  Can you try saving and loading to see if it clears?  Tracking down now whats going on with autosaves.

**Comment by tkapis** [comment]
By autosaves do you also mean quicksaves ? I use those and quickloads a lot via voice activation.

**Comment by KozGit** [comment]
Thanks, that helps!

**Comment by tkapis** [comment]
BTW I am using roomscale and it works fine. The only thing is if you move away from the centre your body doesn't follow which is pretty understandable of course.

How can you delete a save if touch activation is not working ?

**Comment by KozGit** [comment]
Ok, fixed the weapon/PDA scaling issue on quick/autosaves.

@tkapis - what movement mode are you using?  The torso should follow your movements in this build if you physically turn in place.

**Comment by tkapis** [comment]
Move Mode = 'Off Hand = Forward', Turning ='Real Life'.
The torso definitely does not turn with me if I turn in place.

**Comment by KozGit** [comment]
@tkapis Can you post a copy of your config file here ? ( Normally located in c:\users\(your user name)\Saved Games\id Software\DOOM 3 BFG\Fully Possessed - either vr_oculus.cfg or vr_openvr.cfg, depending on what headset you are using.

The body is supposed to be turning now when you turn in real life.  I Just verified here with those move settings - but I would like to check if there is something in the config that is preventing it from working for some reason.  ( You're using touch controllers or vive wands correct? )

Thanks for the help!

**Comment by tkapis** [comment]
Here is the config. I'm using vive controllers.
[vr_openvr.zip](https://github.com/KozGit/DOOM-3-BFG-VR/files/1392650/vr_openvr.zip)

**Comment by KozGit** [comment]
Thanks.  And I just realized I'm not exactly sure which version you are running of the ones 10101000 posted.

Here's a link to the newest version ( with the scaling fix ) - you may want to try this.

https://drive.google.com/file/d/0B-_8Q_oQABjLX0liZEppdVgxVUU/view?usp=sharing

Unzip into your d3 dir and replace all files.

I'll check the config.

**Comment by tkapis** [comment]
Hi KozGit, with the newest version physically turning in place works fine now.

I have one small problem still. I activate the game menu via voice and quite often what happens is it begins to open the menu and then immediately closes it again. I thought that it had to do with my left hand position at that moment if it's too low but now I am not sure if that's the case.

This mod is absolutely brilliant and I thank you very much for creating it.

**Comment by tkapis** [comment]
When using full body, can you maybe improve the positioning of the torso when you move, it seems to swell out and then go back most if the time. Is it possible to fix it more to the player ?

**Comment by CylonSurfer** [comment]
I was looking at the torso, just the other night and thought it was too far forward and got in the way. However if you look down and walk backwards the torso is positioned perfectly. Personly I think that that the torso should remain in the same position for both backward and forward movement, with the backward position being the correct one of the two. It looks similar to the position of the torso I opted for in my Skyrim mod, 'The Joy of Perspective'.

**Comment by cercata** [comment]
The "Fully possessed" Doom 3 BFG mod continues to amaze. Dev Samson made a silent release a couple of weeks ago, I think it went unnoticed by most people

xD

[https://www.reddit.com/r/oculus/comments/7bcv0a/new_version_022_of_doom_3_bfg_vr_released/](url)

**Comment by AerowynX** [comment]
link doesn't work.. kozgit posted a link few posts above but i tried that and it didn't work for me

**Comment by jdawgzim** [comment]
> Added a push to talk button for voice commands. ( vr_voicePushToTalk to enable, then bind to a button in controls->bindings)
Thank you @KozGit  !

If it's not too difficult can we make the weapon grab from the back bindable to an action? Like If I grab my back it always pulls out a shotgun.  Right now it just scrolls through weapons which is unfortunately not helpful :cry:

**Comment by formicsapien** [comment]
@jdawgzim I would LOVE that!  Doesn't seem too hard to implement.  I know it would take a lot more work but I like the idea of being able to store even more like this and have a weapon selection system like in H3VR.
